services:
  db:
    build: ./db
    container_name: pg18_lab2
    restart: unless-stopped
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # scram-sha-256 — метод аутентификации по умолчанию в PG14+, фиксируем явно.
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--locale=ru_RU.UTF-8 --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d labdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  pinger:
    #build: ./pinger
    #image: pinger:1.0
    image: pinger/nerush
    container_name: pinger_lab2
    restart: unless-stopped
    volumes:
      - ./log:/pinger_log
    env_file:
      - ./pinger/pinger.env
    depends_on:
      db:
        condition: service_healthy